-- Reemplazo del dominio: productos -> solicitudes de presupuesto.
DROP TABLE IF EXISTS producto;

CREATE TABLE solicitud_presupuesto (
    id              BIGINT                   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo          VARCHAR(160)             NOT NULL,
    descripcion     VARCHAR(1000)            NOT NULL,
    monto           INTEGER                  NOT NULL,
    solicitante     VARCHAR(320)             NOT NULL,
    estado          VARCHAR(20)              NOT NULL,
    comentario_admin VARCHAR(500),
    creado_en       TIMESTAMP WITH TIME ZONE NOT NULL,
    decidido_en     TIMESTAMP WITH TIME ZONE,

    CONSTRAINT monto_positivo CHECK (monto > 0),
    CONSTRAINT estado_valido CHECK (estado IN ('PENDIENTE', 'APROBADA', 'RECHAZADA'))
);
